# Generated by Django 5.0.3 on 2024-04-04 09:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreastfeedingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField()),
                ('stopTime', models.TimeField()),
                ('breastSide', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('both', 'Both')], max_length=10)),
                ('supplement', models.CharField(choices=[('breastmilk', 'Breastmilk'), ('formula', 'Formula')], max_length=20)),
                ('painLevel', models.PositiveIntegerField()),
                ('nippleShape', models.CharField(choices=[('rounded', 'Rounded'), ('lipstick', 'Lipstick')], max_length=20)),
                ('nippleColor', models.CharField(choices=[('regular', 'Regular'), ('white', 'White'), ('purple', 'Purple')], max_length=20)),
                ('milkBlister', models.BooleanField(default=False)),
                ('nippleCracks', models.BooleanField(default=False)),
                ('feelings', models.CharField(choices=[('relaxed', 'Relaxed'), ('happy', 'Happy'), ('sad', 'Sad'), ('exhausted', 'Exhausted'), ('anxious', 'Anxious')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PoopDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('colour', models.CharField(choices=[('verydark', 'மிகவும் இருண்ட நிறம்'), ('green', 'பச்சை நிறம்'), ('darkbrown', 'அடர் பழுப்பு நிறம்'), ('mustard', 'கடுகு நிறம்'), ('other', 'மற்ற நிறம்')], max_length=50)),
                ('texture', models.CharField(choices=[('liquid', 'திரவம்'), ('pasty', 'பேஸ்டி'), ('hard', 'கடினமான'), ('snotty', 'ஸ்நாட்டி'), ('bloody', 'இரத்தம் தோய்ந்த')], max_length=50)),
                ('size', models.CharField(choices=[('coin', 'நாணயத்தின் அளவு'), ('tablespoon', 'தேக்கரண்டி அளவு'), ('bigger', 'பெரிய அளவு')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sex', models.CharField(choices=[('girl', 'பெண்'), ('boy', 'ஆண்')], default='girl', max_length=4)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
