# Generated by Django 5.0.3 on 2024-04-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Premature',
            field=models.IntegerField(choices=[(0, 'இல்லை'), (1, 'ஆம்')], default=0),
        ),
    ]
