# Generated by Django 5.0.3 on 2024-04-06 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0003_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pregnant',
            field=models.BooleanField(choices=[(False, 'இல்லை'), (True, 'ஆம்')], default=False),
        ),
    ]
