# Generated by Django 5.0.3 on 2024-04-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0005_remove_userinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parentName',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
