# Generated by Django 5.0.3 on 2024-04-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0007_breastfeedingdetail_parentname_userinfo_parentname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breastfeedingdetail',
            name='parentName',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='parentName',
        ),
    ]
