# Generated by Django 5.0.3 on 2024-04-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0008_remove_breastfeedingdetail_parentname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breastfeedingdetail',
            name='parent_Name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
