# Generated by Django 5.0.3 on 2024-04-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0012_remove_breastfeedingdetail_parent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='poopdetail',
            name='ParentName',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
