# Generated by Django 5.0.3 on 2024-04-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0013_poopdetail_parentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='breastfeedingdetail',
            name='parentname',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
