# Generated by Django 5.0.3 on 2024-04-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0015_rename_parentname_breastfeedingdetail_parentname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Premature',
            field=models.IntegerField(),
        ),
    ]
