# Generated by Django 5.0.3 on 2024-04-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0016_alter_product_premature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Premature',
            field=models.IntegerField(choices=[(-4, '26-30'), (-8, '31-39'), (39, '39')], default=0),
        ),
    ]
