# Generated by Django 5.0.3 on 2024-04-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0018_alter_product_premature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Premature',
            field=models.CharField(choices=[(1, '26-30'), (2, '31-39'), (3, '39')], default=0, max_length=6),
        ),
    ]
