# Generated by Django 5.0.3 on 2024-04-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0020_alter_product_premature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Premature',
            field=models.CharField(choices=[('26-30', '26-30'), ('31-39', '31-39'), ('39', '39')], default=0, max_length=6),
        ),
    ]
