# Generated by Django 5.0.3 on 2024-04-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0021_alter_product_premature'),
    ]

    operations = [
        migrations.AddField(
            model_name='breastfeedingdetail',
            name='present_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
