# Generated by Django 5.0.3 on 2024-04-22 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0022_breastfeedingdetail_present_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
