# Generated by Django 5.0.3 on 2024-04-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0026_alter_product_premature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sex',
            field=models.CharField(choices=[('பெண்', 'பெண்'), ('ஆண்', 'ஆண்')], default='girl', max_length=4),
        ),
    ]
