# Generated by Django 5.0.3 on 2024-04-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0027_alter_product_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sex',
            field=models.CharField(choices=[('பெண்', 'பெண்'), ('ஆண்', 'ஆண்')], default='பெண்', max_length=4),
        ),
    ]
