# Generated by Django 5.0.3 on 2024-04-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0034_rename_parentname_poopdetail_parentname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breastfeedingdetail',
            name='breastSide',
            field=models.CharField(choices=[('இடது', 'இடது'), ('வலது', 'வலது'), ('இரண்டும்', 'இரண்டும்')], max_length=10),
        ),
        migrations.AlterField(
            model_name='breastfeedingdetail',
            name='feelings',
            field=models.CharField(choices=[('நிம்மதி', 'நிம்மதி'), ('மகிழ்ச்சி', 'மகிழ்ச்சி'), ('சோகம்', 'சோகம்'), ('exhausted', 'Exhausted'), ('கவலை', 'கவலை')], max_length=20),
        ),
        migrations.AlterField(
            model_name='breastfeedingdetail',
            name='milkBlister',
            field=models.CharField(choices=[('இல்லை', 'இல்லை'), ('ஆம்', 'ஆம்')], max_length=5),
        ),
        migrations.AlterField(
            model_name='breastfeedingdetail',
            name='nippleColor',
            field=models.CharField(choices=[('கருப்பு', 'கருப்பு'), ('வெள்ளை', 'வெள்ளை'), ('சிவப்பு', 'சிவப்பு')], max_length=20),
        ),
        migrations.AlterField(
            model_name='breastfeedingdetail',
            name='nippleCracks',
            field=models.CharField(choices=[('இல்லை', 'இல்லை'), ('ஆம்', 'ஆம்')], max_length=5),
        ),
        migrations.AlterField(
            model_name='breastfeedingdetail',
            name='nippleShape',
            field=models.CharField(choices=[('வட்ட வடிவம்', 'வட்ட வடிவம்'), ('கூம்புவடிவம்', 'கூம்புவடிவம்')], max_length=20),
        ),
        migrations.AlterField(
            model_name='breastfeedingdetail',
            name='supplement',
            field=models.CharField(choices=[('தாய்ப்பால்', 'தாய்ப்பால்'), ('பவுடர்பால்', 'பவுடர்பால்')], max_length=20),
        ),
    ]
