# Generated by Django 5.0.3 on 2024-04-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0035_alter_breastfeedingdetail_breastside_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breastfeedingdetail',
            name='breastSide',
        ),
        migrations.AlterField(
            model_name='breastfeedingdetail',
            name='feelings',
            field=models.CharField(choices=[('relaxed', 'Relaxed'), ('happy', 'Happy'), ('sad', 'Sad'), ('exhausted', 'Exhausted'), ('anxious', 'Anxious')], max_length=20),
        ),
        migrations.AlterField(
            model_name='breastfeedingdetail',
            name='milkBlister',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='breastfeedingdetail',
            name='nippleColor',
            field=models.CharField(choices=[('regular', 'Regular'), ('white', 'White'), ('purple', 'Purple')], max_length=20),
        ),
        migrations.AlterField(
            model_name='breastfeedingdetail',
            name='nippleCracks',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='breastfeedingdetail',
            name='nippleShape',
            field=models.CharField(choices=[('rounded', 'Rounded'), ('lipstick', 'Lipstick')], max_length=20),
        ),
        migrations.AlterField(
            model_name='breastfeedingdetail',
            name='supplement',
            field=models.CharField(choices=[('breastmilk', 'Breastmilk'), ('formula', 'Formula')], max_length=20),
        ),
    ]
