# Generated by Django 5.0.3 on 2024-04-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0037_rename_present_weight_breastfeedingdetail_presentweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='breastfeedingdetail',
            name='breastSide',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
