# Generated by Django 5.0.3 on 2024-04-22 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0038_breastfeedingdetail_breastside'),
    ]

    operations = [
        migrations.AddField(
            model_name='breastfeedingdetail',
            name='submission_date',
            field=models.DateField(default=datetime.date(2024, 4, 22)),
        ),
        migrations.AddField(
            model_name='poopdetail',
            name='submission_date',
            field=models.DateField(default=datetime.date(2024, 4, 22)),
        ),
        migrations.AddField(
            model_name='product',
            name='submission_date',
            field=models.DateField(default=datetime.date(2024, 4, 22)),
        ),
    ]
