# Generated by Django 5.0.3 on 2024-04-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0040_poopdetail_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poopdetail',
            name='size',
        ),
    ]
