# Generated by Django 5.0.3 on 2024-04-23 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0041_remove_poopdetail_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breastfeedingdetail',
            name='submission_date',
            field=models.DateField(default=datetime.date(2024, 4, 23)),
        ),
        migrations.AlterField(
            model_name='poopdetail',
            name='colour',
            field=models.CharField(choices=[('verydark', 'மிகவும் இருண்ட நிறம்'), ('green', 'பச்சை நிறம்'), ('darkbrown', 'அடர் பழுப்பு நிறம்'), ('mustard', 'கடுகு நிறம்')], max_length=50),
        ),
        migrations.AlterField(
            model_name='poopdetail',
            name='submission_date',
            field=models.DateField(default=datetime.date(2024, 4, 23)),
        ),
        migrations.AlterField(
            model_name='poopdetail',
            name='texture',
            field=models.CharField(choices=[('liquid', 'திரவம்'), ('pasty', 'பேஸ்டி'), ('hard', 'கடினமான')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='submission_date',
            field=models.DateField(default=datetime.date(2024, 4, 23)),
        ),
    ]
