# Generated by Django 5.0.3 on 2024-04-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0048_alter_breastfeedingdetail_milkblister_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breastfeedingdetail',
            name='milkBlister',
            field=models.CharField(choices=[('இல்லை', 'இல்லை'), ('ஆம்', 'ஆம்')], default='இல்லை', max_length=50),
        ),
        migrations.AlterField(
            model_name='breastfeedingdetail',
            name='nippleCracks',
            field=models.CharField(choices=[('இல்லை', 'இல்லை'), ('ஆம்', 'ஆம்')], default='இல்லை', max_length=50),
        ),
    ]
