# Generated by Django 5.0.3 on 2024-04-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0050_alter_breastfeedingdetail_milkblister_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breastfeedingdetail',
            name='feelings',
            field=models.CharField(choices=[('நிம்மதியாக', 'நிம்மதியாக'), ('மகிழ்ச்சியான உணர்வு', 'Hமகிழ்ச்சியான உணர்வு'), ('சோக உணர்வு', 'சோக உணர்வு'), ('தீர்ந்து போன உணர்வு', 'தீர்ந்து போன உணர்வு'), ('கவலை உணர்வு', 'கவலை உணர்வு')], max_length=20),
        ),
    ]
