# Generated by Django 5.0.3 on 2024-04-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0052_alter_breastfeedingdetail_breastside'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poopdetail',
            name='colour',
            field=models.CharField(choices=[('கருப்பு நிற மலம்', 'கருப்பு நிற மலம்'), ('சிவப்பு நிற மலம்', 'சிவப்பு நிற மலம்'), ('மென்மையான மற்றும் அடர் பச்சை நிற மலம்', 'மென்மையான மற்றும் அடர் பச்சை நிற மலம்'), ('மஞ்சள் நிற மலம்', 'மஞ்சள் நிற மலம்')], max_length=50),
        ),
        migrations.AlterField(
            model_name='poopdetail',
            name='texture',
            field=models.CharField(choices=[('திரவ அமைப்பு', 'திரவ அமைப்பு'), ('கடினமான அமைப்பு', 'கடினமான அமைப்பு'), ('இரத்தம் கலந்த அமைப்பு', 'இரத்தம் கலந்த அமைப்பு')], max_length=50),
        ),
    ]
