# Generated by Django 5.0.3 on 2024-04-24 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0053_alter_poopdetail_colour_alter_poopdetail_texture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breastfeedingdetail',
            name='submission_date',
            field=models.DateField(default=datetime.date(2024, 4, 24)),
        ),
        migrations.AlterField(
            model_name='poopdetail',
            name='submission_date',
            field=models.DateField(default=datetime.date(2024, 4, 24)),
        ),
        migrations.AlterField(
            model_name='product',
            name='submission_date',
            field=models.DateField(default=datetime.date(2024, 4, 24)),
        ),
    ]
