# Generated by Django 5.0.3 on 2024-05-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tally', '0055_alter_breastfeedingdetail_submission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breastfeedingdetail',
            name='submission_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='poopdetail',
            name='submission_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
